version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  foodgram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
  backend:
    image: qqyall/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - foodgram_db
  frontend:
    image: qqyall/foodgram_frontend:latest
    container_name: foodgram-front
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: qqyall/foodgram_gateway:latest
    container_name: foodgram-proxy
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - foodgram_db
